name: South Actress Bot

on:
  schedule:
    - cron: "10 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: |
          pip install instaloader requests
      - name: Run South Bot
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          IG_SESSIONID: ${{ secrets.IG_SESSIONID }}
        run: |
          cd south
          python bot.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Update South State"
